<?php 
session_start();
if(isset($_SESSION["sess_user"]))
{
unset($_SESSION['sess_user']);
session_destroy();
}
elseif(isset($_SESSION["sess_user_a"]))
{
unset($_SESSION['sess_user_a']);
session_destroy();
}
else
{
unset($_SESSION['sess_user_s']);
session_destroy();	
}
header("location:index.php");
?>
